// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2cQhcISy-Ei0IFQpqCybjebpfukWCf9Q',
    appId: '1:511235065316:web:34b144c037dbb7697fb3f1',
    messagingSenderId: '511235065316',
    projectId: 'finearts-bdeab',
    authDomain: 'finearts-bdeab.firebaseapp.com',
    storageBucket: 'finearts-bdeab.appspot.com',
    measurementId: 'G-JGGNBRXCE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ1M8_gD_CJlFcJnurWnX-kqF1mImB9ls',
    appId: '1:511235065316:android:96a6baeed74301567fb3f1',
    messagingSenderId: '511235065316',
    projectId: 'finearts-bdeab',
    storageBucket: 'finearts-bdeab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkaZY1xt1tBBl4sxCPDB_IiZ3HpymtEXk',
    appId: '1:511235065316:ios:8e5e20ac6afcb6cc7fb3f1',
    messagingSenderId: '511235065316',
    projectId: 'finearts-bdeab',
    storageBucket: 'finearts-bdeab.appspot.com',
    iosBundleId: 'com.example.fineArts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkaZY1xt1tBBl4sxCPDB_IiZ3HpymtEXk',
    appId: '1:511235065316:ios:eb9dbc794a430dc67fb3f1',
    messagingSenderId: '511235065316',
    projectId: 'finearts-bdeab',
    storageBucket: 'finearts-bdeab.appspot.com',
    iosBundleId: 'com.example.fineArts.RunnerTests',
  );
}
